### ISSUE TITLE
Count of results for each search query

### ISSUE THREAD

**Issue by revdancatt** [wcmaart/api#18]
The frontend design calls for a header that says “XXXX total results”. Can we get that in the API? If not, we could maybe remove this feature.

**Comment by revdancatt** [comment]
We can do this two ways, _I think_ one involves changing how we ask for, and get the results, essentially pushing the array of results down one layer. i.e. instead of asking for this...

```
query {
  objects(title: "world", per_page:3) {
    id
    title
  }
}
```

...and getting back...

```
{
  "data": {
    "objects": [
      {
        "id": 6,
        "title": "World of foo"
      },
      {
        "id": 50,
        "title": "World of bar"
      },
      {
        "id": 15,
        "title": "World of baz"
      }
    ]
  }
}
```

We _could_ ask for it like this...

```
query {
  objects(title: "world", per_page:3) {
    records {
      id
      title
    }
    pagination {
      page_size
      current_page
      max_page
      total_count
    }
  }
}
```

So that we get the actual records in the `records` node, and then the counts etc in the `pagination`.

---

_*Or*_

We could two different requests. The first request sends the query in, and gets the count back, i.e.

```
query {
  objectsCount(title: "world", per_page:3) {
      page_size
      current_page
      max_page
      total_count
  }
}
```

Then, we ask for the actual results...

```
query {
  objects(title: "world", per_page:3) {
    id
    title
  }
}
```

The second method means the current collections spelunker doesn't need to change any code, just make an extra call. The down side is we run the search twice. The up side is the site is unlikely to be a 1000s of request per second, so it probably doesn't make _much_ difference. The other up side is sometimes we just want the numbers without the data.

I think the first method is probably the correct but slightly more annoying way.

---

There's more details about Pagination for GraphQL here: https://graphql.org/learn/pagination/

None of which seems to _quite_ match what we want to do.

**Comment by erchaves** [comment]
hey @revdancatt hmm, can't we just include a totalCount in the query we already have? In the graphql pagination docs if you search for totalCount it talks about that right?

**Comment by revdancatt** [comment]
@erchaves When you say "just include" where do you suggest just including it?

Can you show an example of what you mean, say when we're asking for a bunch of `objects`?

In the schema we have defined a bunch of queries and types: https://github.com/wcmaart/api/blob/master/src/modules/schema/index.js

The query for getting `objects` looks like this...

```
objects(
    page: Int,
    per_page: Int,
    object_name: String,
    maker: String,
    period: String,
    medium: String,
    title: String,
    color: String,
    color_threshold: Float = 0.75
    color_source: String = "google"
  ): [Object]
```

The user can only ask for things defined in that query, and graphQL will only give back what the user has asked for. In this case it'll give back an array of `[Object]`s.

So how does the user ask for the totalCount and where would the totalCount be returned in the `data` node?

I think the first suggestion in my first comment is what we're both talking about, but "can't we just include" alludes to something much simpler and I'm really hoping there is 😸
