### ISSUE TITLE
Allow us to get a summary image for events

### ISSUE THREAD

**Issue by erchaves** [wcmaart/api#30]
For events, the logic on the front end to get a summary image can look like this:
`props.keyImage || props.objects[0].remote`
But right now, this never gives us any images. It seems there is never a keyImage. And the objects for the event call is just an array of ids.

**Comment by revdancatt** [comment]
This was a bug, it's fixed now, the following call will get you the key image when calling **events**...

```javascript
query {
  event(id: 119) {
    id
    title
    keyImage {
      status
      original_image_id
      public_id
      version
      signature
      width
      height
      format
    }
  }
}
```

**events** (plural) only returns an array of object ids, this is correct behaviour), you don't need to use `props.objects[0].remote` as there will be no `remote` node in the objects to check. If there's no `keyImage` returned in **events** it means there are either no objects that events, there are objects but they don't exists in the system, or none of the objects in an event have an image. All three of those cases exist.

**event** (single), _will_ return full objects.

**Note:** Even with full objects in a single event `props.objects[0].remote` is not a good way of getting an image as there's no guarantee that the first object will have an image.

**Comment by erchaves** [comment]
Great, thanks! yeah i figured the keyImage is the right way to do it. I'll just take out the objects[0] fallback as it's better to just rely on the keyImage.
